//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaVaccinationSystem.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public long PatientId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string BirthDate { get; set; }
        public string Gender { get; set; }
        public long Phone { get; set; }
        public string Address { get; set; }
        public string VaccineName { get; set; }
        public bool FirstDose { get; set; }
        public bool SecondDoze { get; set; }
        public string FirstDoseDate { get; set; }
        public string ScondDoseDate { get; set; }
    }
}
