//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaVaccinationSystem.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccines
    {
        public string VaccineName { get; set; }
        public long EntryDose { get; set; }
        public string ProduceCountry { get; set; }
        public int VaccineId { get; set; }
    }
}
